### ISSUE TITLE
Connection closed after around 20 minutes

### ISSUE THREAD

**Issue by xispit4** [sandybradley/pyBybitMarketMaker#1]
Hello thanks for making this for Bybit too I have switched there to tests and after around 20 ~ 23 minutes I got a message:

Error : Connection is already closed.

then nothing more happen like the script is dead but I am not a coder I don't know for sure, can you help me help you understand better this behavior ?

thanks again

**Comment by sandybradley** [comment]
Hi,

I reprogrammed to reconnect when the connection closes. Please try and let me know.

**Comment by xispit4** [comment]
Now works fine/better thanks, but still I see the (Error : Connection is already closed.) means the connection is not good ? The other two python script running fine (Deribit and EMX) I don't see this behavior looks more "stable" than this from Bybit (the difference may or may not be the dependencies).

Another thing I found a script to sent messages to Telegram do you think it's a good feature to have ? Like trading notifications/balance and so on

https://github.com/LongandShortio/telegram-bot

**Comment by sandybradley** [comment]
The error message signifies a natural  disconnect, at which point my script re-connects, so it can be ignored. I will look at setting up a heartbeat on the channel so that it doesn’t disconnect in the first place. 

I’ll look at your telegram link.
