### ISSUE TITLE
Where did you get the client.Order.Order_newV2(... - command from?

### ISSUE THREAD

**Issue by LordOberlord** [sandybradley/pyBybitMarketMaker#2]

**Comment by sandybradley** [comment]
https://github.com/bybit-exchange/api-connectors/issues/20

**Comment by LordOberlord** [comment]
I owe you one

**Comment by sandybradley** [comment]
Also
https://github.com/bybit-exchange/api-connectors/blob/master/official-http/python/Endpoints.md
